name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: SecuReg-Update
      run: |
        curl -X POST http://217.160.221.142:9090/Component/Create \
          -H "Content-Type: application/json" \
          -d '{"name":"XYZ3","version":"1.0","url":"ex.com","platform":"java","document_ref":"sdsdsdsd","api_ref":"ahjdshjdhjsd","team_id":"ef9c46ad-567f-45e4-b384-b5cffe5f2ed2","service_id":"10d2478b-c545-42d4-abb0-f5dbe51481b8"}'
